version: "3"


services:
  db:
    image: postgres:16.0-alpine3.17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nititape
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/


volumes:
  db_data:
